### ISSUE TITLE
Rust `Waker`s need to be `Send + Sync`

### ISSUE THREAD

**Issue by Matthias247** [DataDog/glommio#194]
It is currently not possible in Rust to safely define non thread-safe `Waker`s.  They are defined to be [Send](https://doc.rust-lang.org/std/task/struct.Waker.html#impl-Send) and [Sync](https://doc.rust-lang.org/std/task/struct.Waker.html#impl-Sync), and thereby the `RawWaker`s must fulfill those guarantees.

[This commit](https://github.com/DataDog/glommio/commit/26cd86c2a854ce875b1a6f79ffcdb8ab0d10bdab), as well as [the general Waker implementation for glommio tasks](https://github.com/DataDog/glommio/blob/035535a61d1d8e9dc3b64cf0044fb8d48a01354e/glommio/src/task/raw.rs#L180-L303) violate those properties.

Non thread-safe `Waker`s had been part of the earlier async/await design in form a so called `LocalWaker`. However they had been removed from the design in order to simplify it, which unfortunately makes life a bit harder (or slower) for projects like this.

In addition to this [Context is also `Sync`](https://github.com/rust-lang/rust/issues/66481), which is something that wasn't initially planned for and probably still should be fixed.

You might want to consider a different wakeup mechansism than directly referencing the tasks via non-thread safe pointers. [The original RFC](https://github.com/rust-lang/rfcs/blob/master/text/2592-futures.md#rationale-drawbacks-and-alternatives-to-the-wakeup-design-waker) mentioned an alternative implementation using thread-local storage and task IDs which could work. However there is also a drawback with this design: It would never allow for non-local wakeups, since the executor on the other thread would not be found (which might however be less of an issue for this project).

**Comment by laa** [comment]
Hi @Matthias247 , thank you for such useful information both for this and the previous issue.  I also was worried by this misconception but did not have time yet to fully investigate this topic. I will definitely check it. That is not a top priority as for now, but IMHO has to be resolved.

**Comment by laa** [comment]
@Matthias247 I have checked RFC which you linked. We actually already wake up tasks using local reference queue, though this probably is not so obvious from the code. As for executor id, I will do that shortly, so Wakers will not be possible to run on the foreign thread.

**Comment by laa** [comment]
@Matthias247 I have checked the RFC. So what is proposed by the RFC team is to wake task using thread-local queue and check the ID of the executor by assertion. As for now we already use thread-local queue, so the addition of the assertion check will lead to functionally the same behaviour. I understand that the state of the RawWaker still will be shared, but the addition of assertion guard, which inevitably needs to be done to ensure correct functionality of the Waker prevents non-thread-safe state changes into the Waker. I will change code shortly to satisfy this requirement.

**Comment by glommer** [comment]
Thanks for the information @Matthias247.

I would like to see this resolved before we reach the point that I consider glommio production ready. My goal is definitely to play well with the ecosystem at large.

**Comment by glommer** [comment]
@laa we should be probably looking at doing that to the Executor in multitask.rs, not the main executor, if I understand correctly. The multitask Executor is equivalent to an execution queue for us. It is actually confusing that both are called `Executor`, but I didn't know better back then =) The one in multitask is probably better off called a task queue.

Futures don't really belong to an Executor for us, but to a task queue (because they can't move to a different task queue). And if we wake up a task queue that was probably inactive at that point we make it active.

**Comment by glommer** [comment]
@Matthias247 I am a bit confused by this. The Future trait methods still expect a `Waker`, and if that doesn't change it has to be `Sync + Send`.

Doesn't that imply that the `RawWaker` has to be `Send + Sync` too ?

**Comment by laa** [comment]
Hi @glommer the point is the RawTask also does reference counting and making RawWaker Send+Sync equals to making of RawTask Send+Sync. But in reality, if I understand logic underneath correctly we merely need to add assertion guard to the logic.  async-rs does the same. Its RawTasks for a local executor are Sync+Send but because they accept !Send+!Sync Futures they put assertion guard to satisfy this contranct.

**Comment by laa** [comment]
It makes RawTask to be Send+Sync in case of !Send+!Sync future at the sense that it does not generate UB, I suppose the same idea is underneath of assertion guard for the Waker implmentation.

**Comment by laa** [comment]
>@laa we should be probably looking at doing that to the Executor in multitask.rs, not the main executor
@glommer sure, we can try to implement delayed execution of Wake, but we can not put the task into the wrong executor. Which means that we need to do nothing if we call wake from incorrect thread exception of panic of course, Which makes all the rest of changes not needed because of contract violation indicated by panic.

**Comment by laa** [comment]
Found additional confirmation in the blogpost of the "withoutboats" one of the active contributors of Rust - "The second use case is more interesting. There is one thing that indeed cannot be supported without the API distinction: using an Rc, non-atomically reference-counted task. There are still other ways to implement a single-threaded event loop, however: Using the Task IDs technique instead of the reference counting technique. Panic when you wake from another thread, instead of when you move to it. This strategy works completely fine." From https://boats.gitlab.io/blog/post/wakers-ii/ .

**Comment by laa** [comment]
I suppose can even protect ourselves by thread id, not by executor id.  The reasoning for that is very simple, we use an implicit reference to the executor to task into the queue, so even if wake will be called outside of the thread-local scope of executor it will not make any damage. I will try both approaches, will check what is faster and will use it.

**Comment by laa** [comment]
I have tried to use executor id in assertion guard and the numbers of benchmarks (all of them, but I was mostly interested in semaphore and channel benchmarks) are slightly slower and lie in the range of statistical mistake. Sometimes numbers for the implementation with executor-id guard even better. I will send PR soon.

**Comment by laa** [comment]
I have experienced a random crash on a single run of bench task. Probably not related to the change, but I am running Valgrind to be sure that we do not have memory leaks or unsafe deallocations.
Meanwhile results of benchmarking:

```
before change:

cost to run task no task queue:mean - 97.6 ns. 
cost to run task in task queue: mean - 265.8 ns.
cost of sending contended local channel: mean - 92.2 ns
cost of sending uncontended local channel: mean - 11 ns
cost of checking for need_preempt: mean - 1.8 ns
cost of acquiring uncontended semaphore: mean - 11.6 ns
cost of acquiring contended semaphore: mean - 202.4 ns

after change:

cost to run task no task queue: mean - 101.5 ns, +4%
cost to run task in task queue: mean - 272.5 ns, +3%
cost of sending contended local channel: mean - 101 ns, + 10%
cost of sending uncontended local channel: mean - 11 ns, 0%
cost of checking for need_preempt: mean - 2 ns,  +10%
cost of acquiring uncontended semaphore: mean - 14 ns, +21%
cost of acquiring contended semaphore: 209.5 ns - +4%
```

**Comment by laa** [comment]
About the current benches. Thear are bit too simple. Only single run, no warm up cycle.  No stats as result. The best performance tool I have seen is the one embedded in latest versions of JDK. I would try to find similar one in Rust ecosystem and propose the change.

**Comment by glommer** [comment]
I agree the benchmarks are too simple, but I was not very happy with any of the other rust tools for that and I was not about to write my own =)

In particular I looked at criterion. I found it not really that good for asynchronous operations, and because the operations we are measuring are too short (in the order of magnitude of a clock measurement) I found the results to be wildly different between runs.

What we have now is at least useful as a polestar to make sure things are not regressing massively and they are enough to see big deviations, which are the ones that are more interesting at this phase of the project anyway.

If you do find a tool that works better than criterion for what we need I would be happy to look at it.

**Comment by glommer** [comment]
@laa is this fully fixed by #210 or is there anything else to do ?

it seems to me that yes, but github didn't like the way you wrote the fixed string so didn't close this

**Comment by glommer** [comment]
I am closing now manually because it seems to me this was your intent. If anything is still missing let me know

**Comment by laa** [comment]
Hi @glommer, yes, that is already closed. I have GMT +2 timezone so can not answer shortly sometimes.
