### ISSUE TITLE
The `executor::test::test_ping_pong_yield` seems to randomly fail

### ISSUE THREAD

**Issue by zserik** [DataDog/glommio#204]
Sometimes, the `executor::test::test_ping_pong_yield` fails with `assertion failed: counter.get() < 10`, but if rerun, it succeeds.

**Comment by glommer** [comment]
This is one of the flakiest tests we have because it is very subject to noise from the environment. I put some work in making it more robust and the conditions more lax but I fear that if we make it any more lax we'd be better off removing it altogether.

The newer tests for static and dynamic shares probably cover this condition well enough -- do they pass for you?
If they are not flaky I am considering removing the ping pong test.

**Comment by zserik** [comment]
No other tests seems as flaky as the `executor::test::test_ping_pong_yield` test.
