### ISSUE TITLE
Regularly merge the `iou` and `uring-sys` forks with upstream

### ISSUE THREAD

**Issue by zserik** [DataDog/glommio#208]
The https://github.com/glommer/iou and https://github.com/glommer/uring-sys forks should be, if possible, regularly merged or rebased against the upstream crates to prevent an eco-system deviation/split.

**Comment by glommer** [comment]
I agree, and every patch I have in my branch is sent upstream first.
However we depend on unreleased versions of liburing, so until Jens make new releases of liburing that has the code we need in the C layer (that I also added into liburing upstream), we can't really merge.

I am closing this because although a valid issue, I am already tracking and there isn't much we can do at the moment
