### ISSUE TITLE
Question on dma buffer allocation

### ISSUE THREAD

**Issue by thirstycrow** [DataDog/glommio#247]
Is it guaranteed to success when allocating a dma buffer? Is there a size limit for the dma buffer? And how would it go with memory pressure?

https://github.com/DataDog/glommio/blob/master/glommio/src/sys/uring.rs#L626

**Comment by glommer** [comment]
Buffers will be allocated through the system allocator if the io_uring memory is exhausted. Guarantees will be the same as the system allocator. Based on my understanding of the standard allocator you should only see a failure if you exhaust your virtual memory address space.

There is no size limit and no memory pressure mechanisms. I am not a big believer of those things living in the library layer, unless we can come up with a general opt-in, configurable way to make that happen. The decision of when and how to do it should still be with the application but we could provide infrastructure if you have a good idea for an API

For now the best way is to use a `glommio::sync::Semaphore`. You can initialize the `Semaphore` with the maximum amount of memory you want used. New allocations are allowed if there are units in the semaphore, and disallowed otherwise.

**Comment by thirstycrow** [comment]
@glommer Thanks for the explanation! I'm going to add a semaphore to limit memory usage. However, allocation failures may still occur theoretically, if the system memory is highly segmentized and the allocated buffer size is large. So, I hope the allocation method would return a result instead of panic, so the failure could be handled by the application.

**Comment by glommer** [comment]
In my experience, there is no reason to believe that allocation failures will be localized to buffer pools - even if they are the cause of memory pressure.

For example, you can have a very unhealthy overuse of buffer memory that fragments memory so much that makes a statement like `let a = Rc::new(Foo::new())` fail as you can't allocate enough memory to fit a `Foo`. And we cannot for sure recover from that.

It's easy to return errors from buffer allocation in the write path. But it is not easy to return errors from buffer allocation in the read path, that happens inside the reactor (It's doable, just not that direct). So at that point it becomes a harder API to chew for not that clear a gain.
