### ISSUE TITLE
error information is lost

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#270]
Part of the information we encode in errors is lost when we print them.

Take for example this:
```

        if start_id != end_id {
            return Err(GlommioError::<()>::WouldBlock(ResourceType::File(format!(
                "Reading {} bytes from position {} would cross a buffer boundary (Buffer size {})",
                len, self.current_pos, buffer_size
            ))));
        }
```

This very helpful message was supposed to tell us how much we are reading, by how much we failed, etc.

However due to the way we are implementing `Display` for `GlommioError`, the only information that make the output is:

```
thread 'test-1' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: WouldBlock, error: "File operation would block" }',
```

**Comment by glommer** [comment]
@bryandmc can you please take a look ?

**Comment by bryandmc** [comment]
Yeah I'll look at it as soon as I get back tomorrow it's probably an easy
fix. Just gotta tweak the display impl as you suggest.

-Bryan

**Comment by bryandmc** [comment]
Ok so after looking at this I'm starting to think maybe it's worth just getting rid of `thiserror` and doing our own display impl's manually instead of contorting this library to do it. We already did our own impls for other things that it would sometimes offer as well because we had more specific needs so I'm just gonna do that. Bonus: we get to remove a dependency!
