### ISSUE TITLE
Wording in get_buffer_aligned docs

### ISSUE THREAD

**Issue by sstadick** [DataDog/glommio#321]
[Docs](https://docs.rs/glommio/0.3.1/glommio/io/struct.DmaStreamReader.html#method.get_buffer_aligned)

The docs say:

> In order to use this API, one must guarantee that reading the specified length may cross into a different buffer.

What does that mean? In all examples it looks like the returned buffers length is checked to see if it is the same as the buffer size. Does this mean that this will not truncate itself appropriately when it hits the end of a file if the end of a file is not aligned with the buffer size?

Looking at the example [here](https://github.com/DataDog/glommio/blob/ac98da177c615874a5c4e845052c61a6135d27c0/examples/storage.rs#L124) it looks like the end of file scenario is handled appropriately. I just want to make sure I'm not missing something.

**Comment by glommer** [comment]
Hello and cool dinosaur!

Actually the wording should have been **"should not cross"**.

So for instance imagine your position is 4000 and your buffer size is 4096. You cannot ask for a 100-byte read at this point.
We could potentially improve this to return a short read at this point, but I find this potentially confusing because usually short reads are indicative of end-of-file.

What do you think?

**Comment by sstadick** [comment]
Thanks for the speedy reply!

That wording (in your comment) matches up with what I thought it did a little better. I see what you mean about short reads being potentially confusing. 

To clarify a bit more:
- If I'm at position 4096 and the file is 4196 bytes in total, buffer size is 4096, the next call to `get_buffer_aligned` should return 100 bytes to me and this indicates EOF.

If that is the case, I think that is a perfectly fine API and fits the use case of scanning a file really well. It just wasn't clear to me from the docs whether the last 100bytes would be read since they don't fully align to the buffer, and since the docs warn that this is a good method for reading the header of a file, but not for consuming the whole file. 

BTW, I came to glommio via this [post](https://itnext.io/modern-storage-is-plenty-fast-it-is-the-apis-that-are-bad-6a68319fbc1a) from you which was a fantastic read! And I've already been able to put together some naive examples of using glommio which is pretty awesome. Thanks for your work and for making this open source :+1:

**Comment by glommer** [comment]
It's really my pleasure! I haven't yet wrote too much about writes, and I keep thinking it's because it would be uninteresting. May I ask you if an article focused on writes would be a good read in your opinion?

About the documentation, would you like to send us a patch? I'd be truly honoured to have you as a contributor. If not it's ok too, I'll patch that later.

**Comment by sstadick** [comment]
Yes! I'd love to send a PR for the docs! I'll put one together sometime today.

And as for a something on writes, in my opinion that would be super interesting to see. The article that linked to your article, which got me their originally was [this](https://gregoryszorc.com/blog/2021/04/06/surprisingly-slow/). And it had a brief section on writes that made me realize that I understand writes even less than I thought I understood reads. So any exposition on that topic at all would be fantastic.
