### ISSUE TITLE
What is the idomatic method of spawn_blocking in glommio?

### ISSUE THREAD

**Issue by qiujiangkun** [DataDog/glommio#368]
Sometimes I would like to do some side work. Of course I can spin up a dedicated thread pool. Or I can just `std::thread::spawn()` with some core_affinity management. What is the idomatic method of spawning an blocking task in glommio?

https://github.com/najamelan/async_executors/issues/3#issuecomment-855180980

**Comment by bryandmc** [comment]
Generally... try not to..? If you do have to I suppose just spawning a thread and using channels could be your best bet. I suppose we should have a worked example of this somewhere but frankly it's something that should be avoided like the plague and definitely not done in a glommio executor. I'm semi-resistant to this, though it can be pretty easily implemented outside glommio with little or no changes/involvement from glommio. 

Another option might be: https://github.com/smol-rs/blocking, but I'm a little skeptical because it looks like it uses a mutex internally and the last thing you want to do is create unnecessary synchronization between the glommio executor thread and this "worker" blocking thread. This is where the care should be taken. Ideally use a sort of ringbuffer to transfer the work to the worker threads so you don't need to block (at the very least don't block on the glommio side). 

The linked thread references the thread affinity and I suppose it's possible it could be a problem but I'm not enough of an expert in this area to speculate.. My guess is you can just leave them non-affinitized and linux should get the message and schedule it randomly around where there's available resources. Or, if you are worried you could affinitize them to anything that's NOT a glommio thread. But this may be overkill so hopefully someone else will chime in with more definitive answers in that area.

**Comment by qiujiangkun** [comment]
> My guess is you can just leave them non-affinitized

I can just set the cpu mask to 0xFFFF, but it's not the default behavior

**Comment by glommer** [comment]
After recent work we now support channels that connect glommio with other threads.

So indeed the best way is to spawn a thread (or have a thread pool ready), do your work there, and pass the results back on the channel.

If you are interested in working on a generic way to make that happen in glommio, I think we can craft a good API. But the requirement for that to happen should be that it is prohibitively difficult to do it with building blocks outside the main executor API (so we don't become a do-all solve-all)

What would be nice to see:
- a way to safely shut down the thread pool
- a way to make sure panics in the thread pool don't panic the whole executor
- and perhaps more importantly: a way to make sure the thread pool don't become just a way to make us lazy and offload everything there.

**Comment by glommer** [comment]
I just opened https://github.com/DataDog/glommio/pull/398

That doesn't do spawn_blocking, but it implements most of the machinery needed to do it.

On top of the code in that PR, we'd have to : 
1) use a thread pool (1 is ok for syscalls, for arbitrary code you need a few)
2) add an opcode for an arbitrary user function.
3) expose it as API.

**Comment by HippoBaro** [comment]
#501 adds a proper interface for submitting blocking operations: `glommio::executor().spawn_blocking(...)`. It is backed by a thread poll.
