### ISSUE TITLE
Support for offline vendored builds

### ISSUE THREAD

**Issue by mmstick** [DataDog/glommio#466]
The build.rs currently requires Internet access to get some required dependencies at build time. There should be a path for building from pre-fetched vendored sources. Currently unsure on the best approach at the moment.

This is required before we can start using this for projects in Pop!_OS. Interested in experimenting with a Linux-only async runtime with native io_uring support.

**Comment by glommer** [comment]
I agree with the sentiment.

About approaches, internet access should only be required for the submodule step.
Ultimately submodule is just a directory, so we could allow an environment variable to specify which directory you want your code to be at. In the absence of the environment variable we'd still do the submodule build.

Would that work?

Another approach, that is obviously a lot more work, is to ditch C's liburing and use native rust code for that. There are pros and cons of that, the main con is that is just a lot of work for marginal value.

**Comment by mmstick** [comment]
That would be better than the current situation. But perhaps rather than being a submodule, it could be its own Rust crate that's imported as a dev-dependency to the build.rs, so it's automatically wrapped up with `cargo vendor`. Wouldn't mind contributing to an effort to ditch C-based liburing though.

**Comment by glommer** [comment]
because Rust builds everything, if you do have an external crate that just builds the submodule you will end up depending on that at build time, no?

One quick fact: historically, that's how we operated. All the liburing code was part of `iou`. But the maintainer didn't have time to work on the project anymore and their pace was not compatible with our needs, so we ended up importing the code.

The one major downside of io_uring-all-in-rust is that io_uring still evolves pretty fast, and the C liburing is maintained by Jens himself. So features would be harder to adopt. But perhaps this is less of a concern now as things are not as fast paced as before.

What I would propose is to do the env variable for now so that life gets more manageable for you, and long term I'd be happy to agree and work towards a better long term solution.

**Comment by mmstick** [comment]
The way we package software requires that all dependencies are vendored in advance with `cargo vendor`. A source tarball is generated with the project sources and all of its vendored crates. Then the packaging server uses sbuild to build everything in offline chroots. So dev-dependency crates are perfectly fine since they get vendored with `cargo vendor`, but crates that assume there's a functioning Internet connection when `build.rs` is being executed are going to immediately fail.

**Comment by glommer** [comment]
Thanks for clarifying. In the short term I think factoring this out to an external crate is not the way to go. Once more, such crate already exists, it just doesn't get updated. I contacted the author a while ago about becoming the maintainer but didn't hear back, and that just creates confusion.

If you are okay with that, short term we'll use the environment variable, and longer term work towards adopting https://crates.io/crates/io-uring as the low-level `io_uring` layer. That is the pure-rust library that is getting the most attention.
