### ISSUE TITLE
Implement `AsyncWrite` for &DmaStreamWriter

### ISSUE THREAD

**Issue by dignifiedquire** [DataDog/glommio#544]
Looking at the internals of `DmaStreamWriter` it never requires access to `&mut self`, but unfortunately the methods in `AsyncWrite` do so. Currently it is only implemented for `DmaStreamWriter`, but implementing it for `&DmaStreamWriter` would allow me to write using a read reference only. 

Otherwise I am currently stuck, as I have to put the writer into a `RefCell` and borrow across an await point, in order to actually call `write`, when I only have a read reference.

**Comment by glommer** [comment]
to be honest I don't quite know what to do about this, and I have seen myself with similar problems in the past.
Because this is part of the trait, it's pretty hard to go around it.

I guess it makes *some* sense to say that for a linear writer like the streams, writes should not be coming from two fibers anyways, so mutable makes sense. But this happens is way too many traits =p

**Comment by dignifiedquire** [comment]
I went and implemented a version for now, that is based on the pattern I have seen here:  https://github.com/smol-rs/async-io/blob/master/src/lib.rs#L1065 which ends up being really nice as an api user
