### ISSUE TITLE
How to do spmc between shards?

### ISSUE THREAD

**Issue by tontinton** [DataDog/glommio#597]
I want to be able to broadcast a message from a specific shard to all other shards, I can probably solve that by using a Vec of spsc queues, but that seems both wasteful and messier to code.

What do you guys think about adding a spmc queue / channel to glommio?

**Comment by glommer** [comment]
@tontinton In reality I lost the interest in adding more core queues to glommio, because as it turns out, external channels work pretty well. For example: https://docs.rs/async-channel/latest/async_channel/ <== this should work with glommio.
This one is not spmc, but if you in practice have a single producer anyway, it behaves as if.

Would that work for you ?

**Comment by tontinton** [comment]
Actually yeah, didn't think about it, for some reason I assumed that it has to be over io_uring, but queues don't do any I/O...

Thanks, I'll close this issue
